name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        HOTLANE_SERVICE_TOKEN: ${{ secrets.HOTLANE_SERVICE_TOKEN }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_KEY }}
        BRANCH: gh-pages
        folder: live